import { Subscription, resolveMemberNextPaymentDate } from '../types';

export function getSampleSubscriptions(userId: string): Omit<Subscription, 'id' | 'userId'>[] {
  const today = new Date().toISOString().split('T')[0];

  const rawList: Omit<Subscription, 'id' | 'userId'>[] = [
    {
      name: 'Microsoft 365 Ghana 1',
      platformName: 'Microsoft 365 Ghana 1',
      mainUserName: 'Yo (Administrador)',
      category: 'Productividad',
      cost: 13.99,
      billingCycle: 'monthly',
      billingPeriod: 'MONTHLY',
      currency: 'GHS',
      billingDay: 1,
      billingMonth: 1,
      defaultContributionPerUser: 2.99,
      color: '#0078D4',
      iconColorHex: '#0078D4',
      iconType: 'VECTOR',
      iconKey: 'layers',
      icon: 'Layers',
      notes: 'Suscripción Microsoft 365 contratada en Ghana (13,99 GHS/mes). Los miembros aportan en euros.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      members: [
        {
          id: 'mem_m365_1',
          name: 'Álvaro Delgado',
          memberName: 'Álvaro Delgado',
          platform: 'Together Price',
          sharingPlatform: 'Together Price',
          contact: 'alvaro.delgado@outlook.com',
          memberContact: 'alvaro.delgado@outlook.com',
          amount: 2.99,
          contributionAmount: 2.99,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Together Price',
          joinedDate: '2026-01-15',
          lastPaymentDate: today,
          notes: 'Cuenta principal Office 365',
        },
        {
          id: 'mem_m365_2',
          name: 'Lucía Méndez',
          memberName: 'Lucía Méndez',
          platform: 'Sharesub',
          sharingPlatform: 'Sharesub',
          contact: '+34 633112244',
          memberContact: '+34 633112244',
          amount: 2.98,
          contributionAmount: 2.98,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Sharesub',
          joinedDate: '2026-02-01',
          lastPaymentDate: today,
        },
        {
          id: 'mem_m365_3',
          name: 'Roberto Sanz',
          memberName: 'Roberto Sanz',
          platform: 'Directo/Familia',
          sharingPlatform: 'Directo/Familia',
          contact: '+34 644556677',
          memberContact: '+34 644556677',
          amount: 2.98,
          contributionAmount: 2.98,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Bizum',
          joinedDate: '2026-02-10',
          lastPaymentDate: today,
        },
      ],
    },
    {
      name: 'Netflix',
      platformName: 'Netflix',
      mainUserName: 'Yo (Administrador)',
      category: 'Streaming',
      cost: 19.99,
      billingCycle: 'monthly',
      billingPeriod: 'MONTHLY',
      currency: '€',
      billingDay: 14,
      billingMonth: 1,
      defaultContributionPerUser: 5.00,
      color: '#E50914',
      iconColorHex: '#E50914',
      iconType: 'VECTOR',
      iconKey: 'film',
      icon: 'Film',
      notes: 'No compartir contraseñas fuera del grupo. Cada uno usa su propio perfil con PIN.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      members: [
        {
          id: 'mem_1',
          name: 'Marco Ruiz',
          memberName: 'Marco Ruiz',
          platform: 'Together Price',
          sharingPlatform: 'Together Price',
          contact: '+34 612345678',
          memberContact: '+34 612345678',
          amount: 5.00,
          contributionAmount: 5.00,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Joiin / Together Price',
          joinedDate: '2026-01-10',
          lastPaymentDate: today,
          notes: 'Perfil 1',
        },
        {
          id: 'mem_2',
          name: 'Elena Gómez',
          memberName: 'Elena Gómez',
          platform: 'Sharesub',
          sharingPlatform: 'Sharesub',
          contact: 'elena.gomez@gmail.com',
          memberContact: 'elena.gomez@gmail.com',
          amount: 5.00,
          contributionAmount: 5.00,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Sharesub Wallet',
          joinedDate: '2026-02-01',
          lastPaymentDate: today,
          notes: 'Perfil 2',
        },
        {
          id: 'mem_3',
          name: 'David Soler',
          memberName: 'David Soler',
          platform: 'Directo/Familia',
          sharingPlatform: 'Directo/Familia',
          contact: '+34 699112233',
          memberContact: '+34 699112233',
          amount: 5.00,
          contributionAmount: 5.00,
          paymentStatus: 'pending',
          isPaidThisMonth: false,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Bizum',
          joinedDate: '2026-03-05',
          notes: 'Perfil 3 (Hermano)',
        },
      ],
    },
    {
      name: 'Spotify',
      platformName: 'Spotify',
      mainUserName: 'Yo (Administrador)',
      category: 'Música',
      cost: 17.99,
      billingCycle: 'monthly',
      billingPeriod: 'MONTHLY',
      currency: '€',
      billingDay: 28,
      billingMonth: 1,
      defaultContributionPerUser: 3.50,
      color: '#1DB954',
      iconColorHex: '#1DB954',
      iconType: 'VECTOR',
      iconKey: 'music',
      icon: 'Music',
      notes: 'Dirección postal compartida configurada.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      members: [
        {
          id: 'mem_4',
          name: 'Sara Valdés',
          memberName: 'Sara Valdés',
          platform: 'Sharingful',
          sharingPlatform: 'Sharingful',
          contact: '+34 655443322',
          memberContact: '+34 655443322',
          amount: 3.50,
          contributionAmount: 3.50,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Sharingful Pay',
          joinedDate: '2026-02-15',
          lastPaymentDate: today,
        },
        {
          id: 'mem_5',
          name: 'Lucas Morales',
          memberName: 'Lucas Morales',
          platform: 'Spliiit',
          sharingPlatform: 'Spliiit',
          contact: 'lucas.m@hotmail.com',
          memberContact: 'lucas.m@hotmail.com',
          amount: 3.50,
          contributionAmount: 3.50,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Spliiit',
          joinedDate: '2026-03-01',
          lastPaymentDate: today,
        },
        {
          id: 'mem_6',
          name: 'Carlos V.',
          memberName: 'Carlos V.',
          platform: 'Amigos',
          sharingPlatform: 'Amigos',
          contact: '+34 688990011',
          memberContact: '+34 688990011',
          amount: 3.50,
          contributionAmount: 3.50,
          paymentStatus: 'overdue',
          isPaidThisMonth: false,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Bizum',
          joinedDate: '2026-01-20',
          notes: 'Pendiente confirmar Bizum de este mes',
        },
        {
          id: 'mem_7',
          name: 'Ana Belén',
          memberName: 'Ana Belén',
          platform: 'Together Price',
          sharingPlatform: 'Together Price',
          contact: 'anabelen@gmail.com',
          memberContact: 'anabelen@gmail.com',
          amount: 3.50,
          contributionAmount: 3.50,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Together Price',
          joinedDate: '2026-02-10',
          lastPaymentDate: today,
        },
        {
          id: 'mem_8',
          name: 'Pedro Navas',
          memberName: 'Pedro Navas',
          platform: 'Directo/Familia',
          sharingPlatform: 'Directo/Familia',
          contact: '+34 677889900',
          memberContact: '+34 677889900',
          amount: 3.50,
          contributionAmount: 3.50,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Efectivo',
          joinedDate: '2026-01-05',
          lastPaymentDate: today,
        },
      ],
    },
    {
      name: 'ChatGPT Plus / Team',
      platformName: 'ChatGPT Plus / Team',
      mainUserName: 'Yo (Administrador)',
      category: 'IA',
      cost: 30.00,
      billingCycle: 'monthly',
      billingPeriod: 'MONTHLY',
      currency: '€',
      billingDay: 5,
      billingMonth: 1,
      defaultContributionPerUser: 15.00,
      color: '#10A37F',
      iconColorHex: '#10A37F',
      iconType: 'VECTOR',
      iconKey: 'bot',
      icon: 'Bot',
      notes: 'Workspace compartido para proyectos y desarrollo.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      members: [
        {
          id: 'mem_9',
          name: 'Javier Colleague',
          memberName: 'Javier Colleague',
          platform: 'Amigos',
          sharingPlatform: 'Amigos',
          contact: 'javier.dev@work.com',
          memberContact: 'javier.dev@work.com',
          amount: 15.00,
          contributionAmount: 15.00,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Bizum',
          joinedDate: '2026-01-01',
          lastPaymentDate: today,
        },
      ],
    },
    {
      name: 'Disney+',
      platformName: 'Disney+',
      mainUserName: 'Yo (Administrador)',
      category: 'Streaming',
      cost: 13.99,
      billingCycle: 'monthly',
      billingPeriod: 'MONTHLY',
      currency: '€',
      billingDay: 20,
      billingMonth: 1,
      defaultContributionPerUser: 3.50,
      color: '#113CCF',
      iconColorHex: '#113CCF',
      iconType: 'VECTOR',
      iconKey: 'clapperboard',
      icon: 'Clapperboard',
      notes: 'Hogar principal y perfiles secundarios.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      members: [
        {
          id: 'mem_10',
          name: 'GamsGo User 44',
          memberName: 'GamsGo User 44',
          platform: 'GamsGo',
          sharingPlatform: 'GamsGo',
          contact: 'user44@gamsgo.net',
          memberContact: 'user44@gamsgo.net',
          amount: 3.50,
          contributionAmount: 3.50,
          paymentStatus: 'paid',
          isPaidThisMonth: true,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'GamsGo Auto',
          joinedDate: '2026-04-12',
          lastPaymentDate: today,
        },
        {
          id: 'mem_11',
          name: 'Marta T.',
          memberName: 'Marta T.',
          platform: 'Sharesub',
          sharingPlatform: 'Sharesub',
          contact: '+34 622334455',
          memberContact: '+34 622334455',
          amount: 3.50,
          contributionAmount: 3.50,
          paymentStatus: 'pending',
          isPaidThisMonth: false,
          isPendingPayment: false,
          isPendingRemoval: false,
          isPendingRegistration: false,
          paymentMethod: 'Sharesub',
          joinedDate: '2026-05-01',
        },
      ],
    },
  ];

  return rawList.map((sub) => ({
    ...sub,
    members: (sub.members || []).map((m) => ({
      ...m,
      nextPaymentDate: resolveMemberNextPaymentDate(m, sub.billingDay),
      paymentFrequencyValue: m.paymentFrequencyValue || 1,
      paymentFrequencyUnit: m.paymentFrequencyUnit || 'months',
      autoRepeatPayment: m.autoRepeatPayment !== undefined ? m.autoRepeatPayment : true,
    })),
  }));
}
